/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeRouteImport } from './routes/de'
import { Route as EnRouteImport } from './routes/en'
import { Route as FreerideRouteImport } from './routes/freeride'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ItRouteImport } from './routes/it'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as SnowboardRouteImport } from './routes/snowboard'
import { Route as DeSplatRouteImport } from './routes/de/$'
import { Route as EnSplatRouteImport } from './routes/en/$'
import { Route as ItSplatRouteImport } from './routes/it/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const FreerideRoute = FreerideRouteImport.update({
  id: '/freeride',
  path: '/freeride',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const SnowboardRoute = SnowboardRouteImport.update({
  id: '/snowboard',
  path: '/snowboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeSplatRoute = DeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DeRoute,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EnRoute,
} as any)
const ItSplatRoute = ItSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ItRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/freeride': typeof FreerideRoute
  '/gallery': typeof GalleryRoute
  '/it': typeof ItRouteWithChildren
  '/kids': typeof KidsRoute
  '/lessons': typeof LessonsRoute
  '/snowboard': typeof SnowboardRoute
  '/de/$': typeof DeSplatRoute
  '/en/$': typeof EnSplatRoute
  '/it/$': typeof ItSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/freeride': typeof FreerideRoute
  '/gallery': typeof GalleryRoute
  '/it': typeof ItRouteWithChildren
  '/kids': typeof KidsRoute
  '/lessons': typeof LessonsRoute
  '/snowboard': typeof SnowboardRoute
  '/de/$': typeof DeSplatRoute
  '/en/$': typeof EnSplatRoute
  '/it/$': typeof ItSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/freeride': typeof FreerideRoute
  '/gallery': typeof GalleryRoute
  '/it': typeof ItRouteWithChildren
  '/kids': typeof KidsRoute
  '/lessons': typeof LessonsRoute
  '/snowboard': typeof SnowboardRoute
  '/de/$': typeof DeSplatRoute
  '/en/$': typeof EnSplatRoute
  '/it/$': typeof ItSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/de'
    | '/en'
    | '/freeride'
    | '/gallery'
    | '/it'
    | '/kids'
    | '/lessons'
    | '/snowboard'
    | '/de/$'
    | '/en/$'
    | '/it/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/de'
    | '/en'
    | '/freeride'
    | '/gallery'
    | '/it'
    | '/kids'
    | '/lessons'
    | '/snowboard'
    | '/de/$'
    | '/en/$'
    | '/it/$'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/de'
    | '/en'
    | '/freeride'
    | '/gallery'
    | '/it'
    | '/kids'
    | '/lessons'
    | '/snowboard'
    | '/de/$'
    | '/en/$'
    | '/it/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DeRoute: typeof DeRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  FreerideRoute: typeof FreerideRoute
  GalleryRoute: typeof GalleryRoute
  ItRoute: typeof ItRouteWithChildren
  KidsRoute: typeof KidsRoute
  LessonsRoute: typeof LessonsRoute
  SnowboardRoute: typeof SnowboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeride': {
      id: '/freeride'
      path: '/freeride'
      fullPath: '/freeride'
      preLoaderRoute: typeof FreerideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snowboard': {
      id: '/snowboard'
      path: '/snowboard'
      fullPath: '/snowboard'
      preLoaderRoute: typeof SnowboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/$': {
      id: '/de/$'
      path: '/$'
      fullPath: '/de/$'
      preLoaderRoute: typeof DeSplatRouteImport
      parentRoute: typeof DeRoute
    }
    '/en/$': {
      id: '/en/$'
      path: '/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof EnRoute
    }
    '/it/$': {
      id: '/it/$'
      path: '/$'
      fullPath: '/it/$'
      preLoaderRoute: typeof ItSplatRouteImport
      parentRoute: typeof ItRoute
    }
  }
}

interface DeRouteChildren {
  DeSplatRoute: typeof DeSplatRoute
}

const DeRouteChildren: DeRouteChildren = {
  DeSplatRoute: DeSplatRoute,
}

const DeRouteWithChildren = DeRoute._addFileChildren(DeRouteChildren)

interface EnRouteChildren {
  EnSplatRoute: typeof EnSplatRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnSplatRoute: EnSplatRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface ItRouteChildren {
  ItSplatRoute: typeof ItSplatRoute
}

const ItRouteChildren: ItRouteChildren = {
  ItSplatRoute: ItSplatRoute,
}

const ItRouteWithChildren = ItRoute._addFileChildren(ItRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DeRoute: DeRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  FreerideRoute: FreerideRoute,
  GalleryRoute: GalleryRoute,
  ItRoute: ItRouteWithChildren,
  KidsRoute: KidsRoute,
  LessonsRoute: LessonsRoute,
  SnowboardRoute: SnowboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
